language: c
sudo: false
env:
  global:
   - IDEVER="1.8.10"
before_install:
   - wget -O arduino.tar.xz https://downloads.arduino.cc/arduino-${IDEVER}-linux64.tar.xz
   - tar xf arduino.tar.xz
   - mv arduino-${IDEVER} ${HOME}/arduino_ide
   - IDEDIR="${HOME}/arduino_ide"
   - LIBDIR="${IDEDIR}/portable/sketchbook/libraries"
   - mkdir -p "${LIBDIR}"
   - export PATH="${IDEDIR}:${PATH}"
   - cd ${IDEDIR}
   - which arduino
install:
   - arduino --install-library "WiFi101"
   - arduino --install-library "WolkConnect"
   - arduino --install-boards "arduino:sam"

script:
   - cd "Wolkabout/WolkConnect-Arduino"
   - BOARD="arduino:sam:arduino_mkr1000"
   - arduino --verbose-build --verify --board ${BOARD} mysketch/mysketch.ino



