language: c
sudo: false
env:
  global:
   - IDEVER="1.8.10"
before_install:
   - "echo $PWD"
   - wget -O arduino.tar.xz https://downloads.arduino.cc/arduino-${IDEVER}-linux64.tar.xz
   - tar xf arduino.tar.xz
   - mv arduino-${IDEVER} ${HOME}/arduino_ide
   - IDEDIR="${HOME}/arduino_ide"
   - LIBDIR="${IDEDIR}/portable/sketchbook/libraries"
   - mkdir -p "${LIBDIR}"
   - cp -r /home/travis/build/Wolkabout/WolkConnect-Arduino "${LIBDIR}"
   - export PATH="${IDEDIR}:${PATH}"
   - cd ${IDEDIR}
   - which arduino
   - sudo apt-get install libgtest-dev
   - sudo apt-get install cmake # install cmake
   - cd /usr/src/gtest
   - sudo cmake CMakeLists.txt
   - sudo make
 # copy or symlink libgtest.a and libgtest_main.a to your /usr/lib folder
   - sudo cp *.a /usr/lib
install:
   - arduino --install-library "WiFi101"
   - arduino --install-boards "arduino:samd"

script:
   - cd "/home/travis/build/Wolkabout/WolkConnect-Arduino/tests/"
   - cmake .
   - make
   - ./testWolkConnector-Arduino
   - cd "/home/travis/build/Wolkabout/WolkConnect-Arduino"
   - BOARD="arduino:samd:mkr1000"
   - arduino --verbose-build --verify --board ${BOARD} examples/simple/simple.ino
   - arduino --verbose-build --verify --board ${BOARD} examples/full_feature_set/full_feature_set.ino
   



